fix; error TS2304: Cannot find name 'TilesSection'
doesn't happen in ci, but is happening in tinderbox and for some
users.

Seeing as ScrollSection doesn't have the problem, follow the export
and namespace pattern used there.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I4c4916ba7a3ad19275bd8b0f5bc53111b3b30cd5