fix(deploy-dev-env): Fix development environment deployment program failed due to incorrect dependency packages
This fixes the following error message:

```text
Error: Unable to find a match: gumbo*
Error: Unable to install the OxOffice Online build dependencies.
```

Signed-off-by: Buo-ren Lin (OSSII) <buoren.lin@ossii.com.tw>